function [J grad] = nnCostFunction(nn_params, ...
                                   input_layer_size, ...
                                   hidden_layer_size, ...
                                   num_labels, ...
                                   X, y, lambda)
    %[J grad] = nnIterativeCostFunction(nn_params, input_layer_size, hidden_layer_size, num_labels, X, y, lambda);
    [J grad] = nnVectorizedCostFunction(nn_params, input_layer_size, hidden_layer_size, num_labels, X, y, lambda);
end
